plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt) apply false
}

spotless {
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
    // HTML / CSS / JavaScript / JSON: Prettier infers the parser from each file extension.
    format("web") {
        target(
            "composeApp/src/**/*.html",
            "composeApp/src/**/*.css",
            "composeApp/src/**/*.js",
            "composeApp/src/**/*.json",
            "composeApp/*.js",
        )
        targetExclude(
            "**/build/**",
            "**/node_modules/**",
            // Generated by the aboutLibraries plugin; never hand-formatted.
            "**/aboutlibraries.json",
        )
        prettier(libs.versions.prettier.get())
    }
    // TOML (Gradle version catalog): Prettier needs the TOML plugin and parser.
    format("toml") {
        target("gradle/libs.versions.toml")
        prettier(
            mapOf(
                "prettier" to libs.versions.prettier.get(),
                "prettier-plugin-toml" to libs.versions.prettierPluginToml.get(),
            ),
        ).config(
            mapOf(
                "plugins" to listOf("prettier-plugin-toml"),
                "parser" to "toml",
            ),
        )
    }
}
