plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.versionCatalogUpdate)
}

// The only formatter for libs.versions.toml; Prettier is kept away from it because
// the two disagree over bundle arrays. Default pruning is left on: the catalog holds
// only versions referenced via version.ref, so the plugin will drop a version entry
// that nothing references anymore (build-config scalars live in gradle.properties).
// End-of-line comments are dropped on format, so annotate an entry on the line above.
versionCatalogUpdate {
    sortByKey = true
}

spotless {
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
    // HTML / CSS / JavaScript / JSON: Prettier infers the parser from each file extension.
    format("web") {
        target(
            "composeApp/src/**/*.html",
            "composeApp/src/**/*.css",
            "composeApp/src/**/*.js",
            "composeApp/src/**/*.json",
            "composeApp/*.js",
        )
        targetExclude(
            "**/build/**",
            "**/node_modules/**",
            // Generated by the aboutLibraries plugin; never hand-formatted.
            "**/aboutlibraries.json",
        )
        prettier(providers.gradleProperty("npm.prettier").get())
    }
}
