plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.spotless)
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.versionCatalogUpdate)
}

// We use version-catalog-update only to keep libs.versions.toml sorted by key.
// The catalog holds only versions referenced via version.ref, so the plugin's
// default pruning is left on: it will flag a version entry that no library or
// plugin references anymore (build-config scalars live in gradle.properties).
versionCatalogUpdate {
    sortByKey = true
}

spotless {
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
    // HTML / CSS / JavaScript / JSON: Prettier infers the parser from each file extension.
    format("web") {
        target(
            "composeApp/src/**/*.html",
            "composeApp/src/**/*.css",
            "composeApp/src/**/*.js",
            "composeApp/src/**/*.json",
            "composeApp/*.js",
        )
        targetExclude(
            "**/build/**",
            "**/node_modules/**",
            // Generated by the aboutLibraries plugin; never hand-formatted.
            "**/aboutlibraries.json",
        )
        prettier(providers.gradleProperty("npm.prettier").get())
    }
    // TOML (Gradle version catalog): Prettier needs the TOML plugin and parser.
    format("toml") {
        target("gradle/libs.versions.toml")
        prettier(
            mapOf(
                "prettier" to providers.gradleProperty("npm.prettier").get(),
                "prettier-plugin-toml" to providers.gradleProperty("npm.prettierPluginToml").get(),
            ),
        ).config(
            mapOf(
                "plugins" to listOf("prettier-plugin-toml"),
                "parser" to "toml",
            ),
        )
    }
}
