name: Update Compose Multiplatform

on:
  schedule:
    - cron: "17 21 * * *"
  workflow_dispatch:
  push:
    branches:
      - chore/auto-update-compose-and-material3

permissions: {}

jobs:
  update:
    name: Update Compose Multiplatform
    permissions:
      contents: read
    uses: yuyuyuyuyu-dev/update-compose-multiplatform/.github/workflows/update-compose-multiplatform.yml@main
    with:
      update-js-yarn-lock: true
      update-wasm-yarn-lock: true
      jdk-distribution-to-update-yarn-lock: jetbrains
      jdk-version-to-update-yarn-lock: "21"
      app-client-id: ${{ vars.PR_BOT_CLIENT_ID }}
      auto-merge: squash
    secrets:
      app-private-key: ${{ secrets.AUTO_MERGE_APP_PRIVATE_KEY }}
